- assets/script.js
- index.html
created a js file in an assets folder and linked it to html
> created script.js and linked it to html

- assets/bootstrap.css
Added bootstrap style sheet to the assets folder
> added bootstrap stylesheet

- index.html
header and footer sections added to html and i have created a new css file and linked it to the html
> header and footer added to html file and new css file added to assets

- index.html
- created a form to collect user name and email
- added a submit button for the form
- added a 'start quiz' button after the form to start quiz
> 8 create form to collect user info

- assets/styles.css
Added wireframe code to the styles.css file
> added wireframe to styles sheet

- index.html
Linked bootstrap css to index.html
> links bootstrap css to html

- index.html
pls review the buttons added for submit and restart.
>  buttons added for submit and restart.

- index.html
added div for score and feedback in the html file
>  added divs to show score and feedback

- index.html
linked bootstrap java script and linked styles.css and bootstrap.css
> 30 bootstrap java link

- index.html
The card only has three available spots for answer choices. This commit adds a fourth spot for a 'D' option on the default question card.
> adds fourth list item for question card

- index.html
- A place holder for the timer function was added to the HTML.
- It was placed above the quiz question.
> adds placeholder for time

- index.html
> updates nav to row

- index.html
> updated buttons

- assets/styles.css
> 50 style header

- assets/styles.css
> centered footer and form

- assets/script.js
- index.html
> 51 arrange functions properly in the page

- assets/styles.css
- index.html
Added background color to the page
add background color to the card
changed the nav-link to active
added border radius to card, card header, and ul
added border radius to submit and restart button
> 46 color style

- index.html
> 58 update button styles

- assets/script.js
local storage of score and cleaning up js code
> 69 create a js function that creates a scoreboard and displays after quiz ends

- assets/script.js
- index.html
> 70 create a fn to display the results dynamically in the webpage

- assets/script.js
- index.html
- The git pull done before pushing the code broke the EventListener. 
- The new code that broke the EventListener was commented out in this push. 
- This is to be resolved before merging.
> 56 for the user form display an error message if the form is submitted with empty incomplete fields

- assets/script.js
- index.html
function has been changed for form submission and included the error message is input values are empty
> 67 create fn to store the email and username in the local storage

- assets/bootstrap.css
- assets/script.js
- assets/styles.css
- index.html
added switch for themes in the footer element
changed bs-body-bg color in bootstrap.css
added div.form-check.form-switch selector in styles.css to align the text to the left
removed homepage selector
removed unused classes from index.html
> 48 dark light switch

- assets/script.js
> 85 work on the if else for diffrent scenarios to display the error message

- assets/styles.css
- index.html
> updated the background and border width of scorecard

- assets/script.js
- assets/styles.css
> 92 hide next question button till submit quiz button is clicked

- assets/script.js
- index.html
Removed old function for checking and storing userScore
Created new function to check and store userScore
Got score to properly display on the score board
> 81 display score

- assets/script.js
- assets/styles.css
- index.html
funcation was created for showing up the answer wrong or right after the submit button.
> 82 afte each question right or wronh has to show up

- .vscode/settings.json
- assets/script.js
function written for showing answer feedback ,
files changed
script.js 
answer.innerHTML =" right";
> errors fixed

- index.html
> deleted extra score div and submit button

- assets/bootstrap.css
> increased the size of the form text areas

- index.html
deleted the answer button which is dulpcate
> answer button duplicated

- assets/styles.css
> 105 style page

- assets/script.js
> changes the first letter of the first question to upppercase

- assets/bootstrap.css
> adds space between the form text area

- assets/script.js
- index.html
> 79 function to display score after each question

- assets/script.js
added a few lines of code for the blank form function
added a code to stop timer when quiz ends
> tweaked form function and start timer function

- assets/script.js
Added 2 additional quiz questions
> 124 add additional questions

- assets/script.js
- assets/styles.css
- index.html
added border radius to the feedback and score-board identifiers.
changed width of feedback and score-board identifiers to 10%
removed border from feedback identifier
changed text color of Correct and Incorrect in script.js
changed background color of feedback and score-board span
answer span will not appear till the user answers the first question
> 128 style answer score span

- assets/styles.css
Changed background footer of color in dark mode
> changed background color of footer in dark mode

- assets/styles.css
Changed width to max-width with value of 12% for feedback and score-board identifiers
> changed width to max-width in feedback and score-board identifiers
